Fix some errors
sakuramipha/citra-web pull request #1
Opened 2023-07-08 20:16 UTC by GPUCode

2023-07-09 07:26 UTC, SleepingSnakezzz requested changes
Let's hope I got them all :P

2023-07-09 07:26 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +It's a given that all great movies get a sequel. And because the first refactor was so good, we decided to make a second one! Well, not quite, but we promise this one is worthwhile too. More specific
```suggestion
It's a given that all great movies get a sequel. And because the first refactor was so good, we decided to make a second one! Well, not quite, but we promise this one is worthwhile too. More specifically it contained the last pieces needed to fully abstract the video core from OpenGL, fixed a handful of regressions from the first one, and even provided some performance improvements.
```

2023-07-09 07:26 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Due to the large amount of changes introduced by the previous PR it was natural for some regressions to slip up the cracks. As we learned the hard way, messing with many parts of the GPU emulation at
```suggestion
Due to the large amount of changes introduced by the previous PR, it was natural for some regressions to slip up the cracks. As we learned the hard way, messing with many parts of the GPU emulation at the same time can result in strange bugs. An example: players of Digimon World Decode [reported](https://github.com/citra-emu/citra/issues/6481) that some models went missing after the merge, which was caused by an erroneous change to the OpenGL viewport.
```

2023-07-09 07:26 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Next, let's talk about Disney. Not the company, but a pretty obscure game they made for the Nintendo 3DS called Disney Art Academy, where you get to draw Mickey Mouse and his friends using the touchs
```suggestion
Next, let's talk about Disney. Not the company, but a pretty obscure game they made for the Nintendo 3DS called Disney Art Academy, where you get to draw Mickey Mouse and his friends using the touchscreen and stylus. Given the nature of the mechanics of the game, where the use of the touchscreen and stylus is centralized, not many people choose to emulate this title. So we were surprised when a bug report came in, stating that the game had become completely broken after the first refactor.
```
Else it'd sound like we're calling the bug reported childish 😅

2023-07-09 07:26 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +After some digging, GPUCode found out that the new mipmap implementation was the culprit that robbed Mickey of his face. To go into more detail, texture downloads were not adjusted to account for mul
```suggestion
After some digging, GPUCode found out that the new mipmap implementation was the culprit that robbed Mickey of his face. To go into more detail, texture downloads were not adjusted to account for multi-level surfaces and thus readbacks of these surfaces did not function correctly. Rendering and reading back from multi-level surfaces is quite unusual and not something we often see in games. Regardless, we are happy it was reported to us so that we could promptly fix it!
```

2023-07-09 07:26 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Alright, what about the performance improvement then? Indeed, by changing the data structure used to store surfaces, Citra is able to cache and search for them more quickly and efficiently. The old i
```suggestion
Alright, what about the performance improvement then? Indeed, by changing the data structure used to store surfaces, Citra is now able to cache and search for them more quickly and efficiently. The old interval map was ditched in favour of a simple page table. Memory locality has also been improved by taking [inspiration](https://github.com/citra-emu/citra/blob/master/src/common/slot_vector.h) from [yuzu](https://yuzu-emu.org/)'s texture cache. All in all, this change should yield a couple of extra frames in games that perform many cache operations and especially in cases where the interval map would become [slow](https://github.com/citra-emu/citra/pull/5183).
```
"would become slow"? is that right?

2023-07-09 19:19 UTC, GPUCode commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +{{< mp4 src="mii.mp4" >}}
It does for me, you may need to refresh the site a few times

2023-07-09 19:20 UTC, GPUCode commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +{{< mp4 src="eula.mp4" >}}
None of the mp4 files have a description. And I've added one for all the images

2023-07-09 19:28 UTC, GPUCode commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +After the afformentioned APT improvements had been merged we started receiving reports of certain games like Braverly Second [crashing](https://github.com/citra-emu/citra/issues/6361). Steveice inves
Added a mention about Mii selection as well

2023-07-09 19:29 UTC, GPUCode commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Alright, what about the performance improvement then? Indeed, by changing the data structure used to store surfaces, Citra is able to cache and search for them more quickly and efficiently. The old i
Replaced it with "interval map lookups would slow things down", sounds more natural

2023-07-09 19:34 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +{{< mp4 src="mii.mp4" >}}
Yes, works after refreshing 5 times for some reason.

2023-07-09 19:47 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +After the afformentioned APT improvements had been merged we started receiving reports of certain games like Bravely Second: End Layer [crashing](https://github.com/citra-emu/citra/issues/6361). This
```suggestion
After the afformentioned APT improvements had been merged we started receiving reports of certain games like Bravely Second: End Layer [crashing](https://github.com/citra-emu/citra/issues/6361). This game, as well as others, crashed when the Mii selection dialog was activated. In the absence of system files, Citra will use an open source replacement for Miis. After setting up the HOME menu though, there's no need to use the replacement and the native 3DS selection will be shown. Any Miis you create through Mii Maker will be available in the games you play! However, none of that would be relevant, if the native selection always crashed, right? So, Steveice10 investigated the issue and discovered that the now more accurate applet handling had exposed further inaccuracies. More specifically, problems arose when CancelLibraryApplet was called on an applet that hadn't started yet, as it would fail to receive the cancellation message and de-register itself.
```

2023-07-10 00:20 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +{{< mp4 src="eula.mp4" >}}
Ham has already requested those so I'm gonna update them myself

2023-07-10 00:29 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Even if one managed to bypass the broken EULA, completing the HOME menu setup still wasn't possible! Reaching the parental controls setup screen the emulator would warn the user of a fatal error, wit
```suggestion
Even if one managed to bypass the broken EULA, completing the HOME menu setup still wasn't possible! Upon reaching the Parental Controls setup screen, the emulator would warn the user of a fatal error, with the only options being either continuing, which would freeze Citra, or aborting entirely. This was the last piece of the puzzle to make the setup screen fully usable and it had to be resolved.
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Following the advice given by the popup and looking at the generated log files, developer SachinVin spotted some configuration blocks Citra was missing and were being accessed by the setup screen. Ad
```suggestion
Following the advice given by the popup and looking at the generated log files, developer SachinVin spotted some configuration blocks Citra was missing and were being accessed by the setup screen. Adding those missing [config's](https://www.3dbrew.org/wiki/Config_Savegame) fixed opening the Settings applet and, combined with the improved applet state management, allowed the system setup to be completed.
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Unfortunately, this wasn’t the end. After performing some tests, former Citra developer [wwylele](https://github.com/wwylele) determined that the solution was not accurate to the hardware and could p
```suggestion
Unfortunately, this wasn’t the end. After performing some tests, Citra developer [wwylele](https://github.com/wwylele) determined that the solution was not accurate to the hardware and could potentially break games. Due to this, the proposed solution could not be accepted into the codebase.
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +We would like to credit Nerrel for providing us with this awesome demonstration of how normal maps can enhance games like Majoras Mask. They have started working on incorporating this feature in thei
```suggestion
We would like to credit [Nerrel](https://www.youtube.com/@Nerrel) for providing us with this awesome demonstration of how normal maps can enhance games like The Legend of Zelda: Majora's Mask 3D. They have started working on incorporating this feature in their [MM3DHD](https://github.com/DeathWrench/MM3DHD) project and we are definitely excited to see the results of this endeavour.
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +It's a given that all great movies get a sequel. And because the first refactor was so good, we decided to make a second one! Well, not quite, but we promise this one is worthwhile too. More specific
```suggestion
It's a given that all great movies get a sequel. And because the first refactor was so good, we decided to make a second one! Well, not quite, but we promise this one is worthwhile too. More specifically, it contained the last pieces needed to fully abstract the video core from OpenGL, fixed a handful of regressions from the first one, and even provided some performance improvements.
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Due to the large amount of changes introduced by the previous PR, it was natural for some regressions to slip up the cracks. As we learned the hard way, messing with many parts of the GPU emulation a
```suggestion
Due to the large amount of changes introduced by the previous PR, it was natural for some regressions to slip through the cracks. As we learned the hard way, messing with many parts of the GPU emulation at the same time can result in strange bugs. For example, players of Digimon World Re:Digitize: Decode [reported](https://github.com/citra-emu/citra/issues/6481) that some models went missing after the merge, which was caused by an erroneous change to the OpenGL viewport.
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +    "digimonfix.png=Oh here" >}}
```suggestion
    "digimonfix.png=Oh, here!" >}}
```

2023-07-10 00:44 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +    title="This will haunt the writer's dreams" >}}
```suggestion
    title="This will haunt our dreams..." >}}
```
I get what you're saying with this, kinda copying what Golden says, but they only have one person working on them whilst we have a few. So makes more sense to say "our" instead

2023-07-10 00:50 UTC, GPUCode commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Following the advice given by the popup and looking at the generated log files, developer SachinVin spotted some configuration blocks Citra was missing and were being accessed by the setup screen. Ad
configs is meant as plural here

2023-07-10 00:56 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Following the advice given by the popup and looking at the generated log files, developer SachinVin spotted some configuration blocks Citra was missing and were being accessed by the setup screen. Ad
All good, ignore this one then :)

2023-07-10 01:01 UTC, merged