Add missing stuff
sakuramipha/citra-web pull request #2
Opened 2023-07-12 22:29 UTC by GPUCode

* Clarify what MoltenVk means and that apple doesn't natively support vulkan
* Rework message that vulkan is available in canary
* Add Qt 6 section
* Mention that canary fixes suspend for 3D Land/Pokemon

2023-07-12 23:06 UTC, SleepingSnakezzz requested changes
hissss

2023-07-12 23:06 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Out with the old and in with the new! Citra has now migrated to Qt6, which brings with it many benefits such as improved [HiDPI support](https://doc.qt.io/qt-6/highdpi.html#conceptual-model), reworke
```suggestion
Out with the old and in with the new! Citra has now migrated to Qt6, which brings with it many benefits such as improved [HiDPI support](https://doc.qt.io/qt-6/highdpi.html#conceptual-model), reworked [multimedia libraries](https://doc.qt.io/qt-6/qtmultimedia-changes-qt6.html), as well as better [styling support for Windows](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5). Needless to say, quite a few changes were needed to be able to support this new API, with the camera implementation being one of the most challenging parts due to the aforementioned multimedia changes. As a result of this change, it's important to mention that, alongside other projects like [Dolphin](https://el.dolphin-emu.org/blog/2022/07/07/dolphin-progress-report-may-and-june-2022/?cr=el), Citra has now dropped support for Windows 7, Windows 8, and 8.1, making Windows 10 becoming the minimum required version. A dwindling user base, combined with security concerns due to lack of regular security updates, have contributed to our decision to make the jump to Qt6, and drop support for these operating systems to focus on their more modern successors.
```
I don't think I've ever heard of qt being referred to as an "API". Is that actually correct?

2023-07-12 23:06 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Out with the old and in with the new! Citra has now migrated to Qt6, which brings with it many benefits such as improved [HiDPI support](https://doc.qt.io/qt-6/highdpi.html#conceptual-model), reworke
Hmm? My changes don't appear to be highlighted in the suggested change box for some reason.

2023-07-12 23:06 UTC, SleepingSnakezzz commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +The changes don't stop there however. With the introduction of Qt6 Steveice10 also completely reworked the way Qt dependencies are handled. Instead of needing to manually build and package Qt release
```suggestion
The changes don't stop there. With the introduction of Qt6 Steveice10 also completely reworked the way Qt dependencies are handled. Instead of needing to manually build and package Qt releases on our [ext-windows-bin](https://github.com/citra-emu/ext-windows-bin), Citra's build system now uses [aqtinstaller](https://github.com/miurahr/aqtinstall), which automatically downloads prebuilt binaries directly from Qt's servers. An added bonus is that we also get more flexibility when it comes to upgrading or adding new Qt libraries!
```

2023-07-12 23:20 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Out with the old and in with the new! Citra has now migrated to Qt6, which brings with it many benefits such as improved [HiDPI support](https://doc.qt.io/qt-6/highdpi.html#conceptual-model), reworke
They are changed, GitHub is just being weird

2023-07-13 00:18 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +Additionally, some titles (e.g. Super Mario 3D Land) can crash if you try to close them from the HOME menu. This is because some services, required for cleaning up kernel resources, are unimplemented
```suggestion
Additionally, some titles (e.g. Super Mario 3D Land) can crash if you try to close them from the HOME menu. This is because some services, required for cleaning up kernel resources, are unimplemented currently. Most built-in titles, such as Mii Maker or Nintendo 3DS Sound, should work fine, however. Our experimental Canary builds contain some fixes for these aforementioned issues. These fixes still need more testing before being merged into Nightly though, so we encourage you to give it a try and report any bugs you come across!
```

2023-07-13 00:25 UTC, sakuramipha commented on site/content/entry/citra-progress-report-2023-q2/index.md
> +The changes don't stop there. With the introduction of Qt6 Steveice10 also completely reworked the way Qt dependencies are handled. Instead of needing to manually build and package Qt releases on our
```suggestion
The changes don't stop there. With the introduction of Qt6, Steveice10 also completely reworked the way Qt dependencies are handled. Instead of needing to manually build and package Qt releases on our [ext-windows-bin](https://github.com/citra-emu/ext-windows-bin), Citra's build system now uses [aqtinstaller](https://github.com/miurahr/aqtinstall), which automatically downloads prebuilt binaries directly from Qt's servers. An added bonus is that we also get more flexibility when it comes to upgrading or adding new Qt libraries!
```

2023-07-15 15:19 UTC, sakuramipha approved these changes

2023-07-15 15:20 UTC, merged